### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Maxopoly** [DevotedMC/EasyHelpOP#1]
Please add a license so others can fork this while knowing what they are dealing with.

@bigbrainiac10

**Comment by ProgrammerDan** [comment]
@bigbrainiac10

I would prefer if you licensed your portions under this: 
https://github.com/DevotedMC/CivModCore/blob/master/License.txt

adapt to your name of course.

If you do I'm happy to leave my fixes in.

**Comment by ProgrammerDan** [comment]
Added.
